name: Time2Eat
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  path_provider: '>=0.3.0'
  sqflite: any
  outline_material_icons: ^0.1.0
  tuple: ^1.0.2
  date_utils: ^0.1.0
  image_picker: ^0.4.10
  dragable_flutter_list: ^1.0.1
  flutter_duration_picker: "^1.0.0"
  side_header_list_view: ^0.0.4
  fluttertoast: ^2.0.9
  flutter_statusbarcolor: any
  flutter_local_notifications: ^0.4.1+1
  shared_preferences: ^0.4.3
  url_launcher: ^3.0.3
  flutter_picker: ^1.0.5
  share: any
  flutter_speed_dial: ^1.0.9
  json_annotation: ^2.0.0
  simple_permissions: ^0.1.9
  http: ^0.12.0
  share_extend: ^1.0.2
  flutter_document_picker: ^1.2.0
  flare_flutter: ^1.0.4
  sentry: any
  flutter_svg: ^0.8.2
  flutter_markdown: ^0.2.0
  archive: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: "images/android_logo.png"
  image_path: "images/ios_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ios_logo.png
    - images/android_logo.png
    - images/logo_transparent.png
    - images/trash.svg
    - images/start.svg
    - images/reminder.svg

    - start_recipe/Thunfischfilet.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Google-Sans
      fonts:
        - asset: fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 800
        - asset: fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/GoogleSans/GoogleSans-Italic.ttf
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 300
        - asset: fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-Regular.ttf
          weight: 400
    - family: Noto-Sans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Bold.ttf
          weight: 800
        - asset: fonts/NotoSans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 300
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
